exec-once = kill kded6
exec-once = hyprpaper
exec-once = hyprpanel
exec-once = hypridle -c ~/.config/hypr/hypridle.conf
exec-once = corectrl --minimize-systray
exec-once = ~/.config/hypr/scripts/moveOpenedGames.sh

# --- Choose Only One --- #
#exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = /usr/lib/polkit-kde-authentication-agent-1
#exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
