# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(alacritty)$,title:^(alacritty)$
windowrule = float, class:^(org.pulseaudio.pavucontrol)
windowrule = float, class:^()$,title:^(Save File)$
windowrule = float, class:^()$,title:^(Open File)$
windowrule = float, class:^(blueman-manager)$
windowrule = float, class:^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
windowrule = float, class:^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$
windowrule = float, class:^(CachyOSHello)$
windowrule = float, class:^(zenity)$

windowrule = float, class:^(thunar)$,title:^(Rename.*)$
windowrule = float, class:^(org.kde.plasma-systemmonitor)$
windowrule = float, class:^(alacritty)$,title:^(nmtui.*)$
windowrule = float, title:^(Picture-in-Picture)$
windowrule = float, class:^(steam)$,title:^(Friends List)$
windowrule = float, class:^(steam)$,title:^(Steam - Self Updater)$

# maximize and tile all steam games (since floating as your monitor res is weird)
# sometimes games get put in a "pseudo" fullscreen which doesnt hide my bar...
# That's annoying as hell! So we force this behavior :D
windowrule = tile, class:^(steam_app_.*)$
windowrule = fullscreen, class:^(steam_app_.*)$

windowrule = size 960 540, title:^(Picture-in-Picture)$
windowrule = center, title:^(Picture-in-Picture)$
windowrule = size 350 800, class:^(steam)$,title:^(Friends List)$
windowrule = center, class:^(steam)$, title:^(Friends List)$
windowrule = size 1434 916, class:^(org.kde.plasma-systemmonitor)$
windowrule = center, class:^(org.kde.plasma-systemmonitor)$


# Ignore maximize requests from apps. You'll probably like this.
#windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
