background      = rgba(0d0d14ff)
base            = rgba(13131eff)
alternate_base  = rgba(1a1a2aff)
text            = rgba(e0d9f0ff)
bright_text     = rgba(d699b6ff)

accent           = rgba(d699b6ff)
accent_secondary = rgba(a79ad4ff)

rounding_large = 10
rounding_small = 5

font_family           = JetBrains Mono
font_family_monospace = JetBrains Mono

font_size       = 11
small_font_size = 10
h1_size         = 19
h2_size         = 15
h3_size         = 13